imports:
    - php

filter:
    paths:
        - src/*

tools:
    external_code_coverage: true

    php_code_sniffer:
        enabled:              true
        config:
            standard:         PSR2