language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - sh -c "if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi"
