language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - ./vendor/bin/coveralls -v