language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --dev
  - wget https://scrutinizer-ci.com/ocular.phar

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - sh -c "if [ $TRAVIS_PHP_VERSION = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi"
